#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct  4 14:50:17 2022

@author: alexander
"""

from Lesson_04 import Sigma
Sigma02_45=350
SigmaB_45=578
Ag_45=0.5
#
#
PlasticStrain=list(range(0,11))
PlasticStress=list(range(0,11))
for i in PlasticStrain:
    PlasticStrain[i]=PlasticStrain[i]*0.05
    PlasticStress[i]=Sigma(Sigma02_45, SigmaB_45, Ag_45, PlasticStrain[i])
#
#

    